name: "Jfrog"

on:
  push:
    branches: 
      - main
      - feature/Jfrog-integration
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  packaging:
    name: Packaging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      projectName: tenx-client

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Jfrog Artifactory
        uses: docker/login-action@v1
        with:
          registry: scybersdev.jfrog.io/
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}